version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.1

jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/configure:
          profile-name: example

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli:
          context: aws